on: [push]

name: stable channel

jobs:
  build_and_test:
    name: Tight Container CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os  }}-cargo-${{ hashFiles('**/Cargo.lock')  }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features
